language: java
jdk: oraclejdk8
install: true
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package verify install sonar:sonar
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.m2
    - '$HOME/.sonar/cache'
addons:
  sonarqube:
    organization: fpezzati-github
    token:
      secure: 657cc270579cc2b13eef89e20505f7673869017a