---
swagger: "2.0"
info:
  version: "0.0.1"
host: "localhost:8080"
basePath: "/YoOffer/srv"
schemes:
- "http"
paths:
  /offer:
    post:
      operationId: "create"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Offer"
      responses:
        default:
          description: "successful operation"
    put:
      operationId: "update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Offer"
      responses:
        default:
          description: "successful operation"
  /offer/pick:
    put:
      operationId: "pick"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Offer"
      responses:
        default:
          description: "successful operation"
  /offer/{id}:
    get:
      operationId: "read"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
    delete:
      operationId: "delete"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
definitions:
  ObjectId:
    type: "object"
    properties:
      timestamp:
        type: "integer"
        format: "int32"
      machineIdentifier:
        type: "integer"
        format: "int32"
      processIdentifier:
        type: "integer"
        format: "int32"
      counter:
        type: "integer"
        format: "int32"
      timeSecond:
        type: "integer"
        format: "int32"
      time:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        format: "date-time"
  Offer:
    type: "object"
    required:
    - "amount"
    - "ownerId"
    properties:
      _id:
        $ref: "#/definitions/ObjectId"
      title:
        type: "string"
        minLength: 0
        maxLength: 50
        pattern: "[\\w\\s]*"
      desc:
        type: "string"
        minLength: 0
        maxLength: 200
        pattern: "[\\w\\s]*"
      ownerId:
        $ref: "#/definitions/ObjectId"
      price:
        type: "number"
        format: "double"
        minimum: 0.0
        maximum: 999999.99
      amount:
        type: "integer"
        format: "int32"
        minimum: 1.0
        maximum: 9.99999999E8
      lat:
        type: "number"
        format: "double"
        minimum: -180.0
        maximum: 180.0
      lon:
        type: "number"
        format: "double"
        minimum: -90.0
        maximum: 90.0
